apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
namespace: default
images:
  - name: 720661188902.dkr.ecr.us-east-1.amazonaws.com/backend
    newName: $IMAGE_REGISTRY/backend   
    newTag: $IMAGE_TAG                 
